newarkshop/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_site.urls', namespace='main_site')),
    path('users/', include('users.urls', namespace='users')),
    path('payments/', include('payments.urls', namespace='payments')),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#     import debug_toolbar
#     urlpatterns = [
#       path(r'^__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns

payments/urls.py
from django.urls import path
from . import views

app_name = 'payments'

urlpatterns = [
    # path('', views.PaymentPageView.as_view(), name='payment'),
    path('', views.home, name='payment'),
    path('charge/', views.charge, name='charge')
]

users/urls.py
"""Defines url patterns for users."""

from django.urls import path, re_path
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm
from django.urls import reverse_lazy
from django.conf import settings

app_name = 'users'

urlpatterns = [
    # Login page.
    path('login/', auth_views.LoginView.as_view(
        template_name='users/login.html', authentication_form=LoginForm
    ), name='login'),
    path('logout/', views.logout_view, name='logout'),

    path('register/consumer/stepOne', views.register_step_one, name='registerConsumerStepOne'),
    path('register/consumer/stepTwo', views.register_step_two, name='registerConsumerStepTwo'),
    path('register/consumer/stepThree', views.register_step_four, name='registerConsumerStepThree'),

    path('register/vendor/stepOne', views.register_step_one, name='registerVendorStepOne'),
    path('register/vendor/stepTwo', views.register_step_two, name='registerVendorStepTwo'),
    path('register/vendor/stepThree', views.register_step_three, name='registerVendorStepThree'),
    path('register/vendor/stepFour', views.register_step_four, name='registerVendorStepFour'),

    path('password_change', auth_views.PasswordChangeView.as_view(
            template_name='users/password_change.html',
            success_url=reverse_lazy('users:password_change_done')
        ),
        name='change_password'),
    path(r'^password_change/complete/$', auth_views.PasswordResetCompleteView.as_view(
                template_name='users/password_change_complete.html'
            ), name='password_change_done'),

    # re_path(r'^password_reset/$', views.password_reset_view, name='password_reset'),
    #re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    #         views.password_reset_confirm, name='password_reset_confirm'),

    re_path(r'^password_reset/$', auth_views.PasswordResetView.as_view(
        template_name='users/password_reset.html',
        email_template_name='users/password_reset_email.html',
        subject_template_name='users/password_reset_subject.txt',
        from_email=settings.DEFAULT_FROM_EMAIL,
        success_url=reverse_lazy('users:password_reset_done')
        ),
        name='password_reset'
    ),
    re_path(r'^password_reset/done/$', auth_views.PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'
    ), name='password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            auth_views.PasswordResetConfirmView.as_view(
                template_name='users/password_reset_confirm.html',
                success_url=reverse_lazy('users:password_reset_complete')
            ), name='password_reset_confirm'),
    re_path(r'^reset/complete/$', auth_views.PasswordResetCompleteView.as_view(
                template_name='users/password_reset_complete.html'
            ), name='password_reset_complete'),
]

payments/models.py
from django.db import models

# Create your models here.

payments/views.py
import stripe

from django.conf import settings
from django.views.generic.base import TemplateView
from django.shortcuts import render

from users.models import CustomUser, UserPaymentInfo

stripe.api_key = settings.STRIPE_SECRET_KEY


# class PaymentPageView(TemplateView):
#     template_name = 'payments/home.html'
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['key'] = settings.STRIPE_PUBLISHABLE_KEY
#         return context
def home(request):
    pay_info = UserPaymentInfo.objects.get(user_id=request.user.id)
    amount_dollar = int(pay_info.pay_amount)
    amount_cent = amount_dollar * 100
    context = {
        'key': settings.STRIPE_PUBLISHABLE_KEY,
        'amount_dollar': amount_dollar,
        'amount_cent': amount_cent
    }
    return render(request, 'payments/home.html', context)


def charge(request):
    pay_info = UserPaymentInfo.objects.get(user_id=request.user.id)
    amount_dollar = int(pay_info.pay_amount)
    amount_cent = amount_dollar * 100

    if request.method == 'POST':
        charge = stripe.Charge.create(
            # amount=500,
            amount=amount_cent,
            currency='usd',
            description='A Django charge',
            source=request.POST['stripeToken']
        )
        context = {'amount_dollar': amount_dollar}
        return render(request, 'payments/charge.html', context)

templates/payments/charge.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Payment Result
                </div>
                <div class="panel-body">
                    <h4>Thanks, you paid <strong>${{ amount_dollar }}</strong>!</h4>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/payments/home.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Please submit monthly subscription
                </div>
                <div class="panel-body">
                    <h5>${{amount_dollar}} for pay</h5>
                    <form action="{% url 'payments:charge' %}" method="post">
                        {% csrf_token %}
                        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                                data-key="pk_test_XtLLhorcPhTY87TZIja6Eq2K"
                                data-description="Card Information"
                                data-amount="{{amount_cent}}"
                                data-locale="auto">
                        </script>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}