main_site/urls.py
from django.urls import path, re_path

from . import views

app_name = 'main_site'

urlpatterns = [
    # Home page.
    path('', views.index, name='index'),
    path('admin/dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('admin/dashboard/transactions', views.admin_transactions, name='admin_transactions'),
    path('admin/dashboard/users', views.admin_users, name='admin_users'),
    path('admin/dashboard/users/delete/(?P<user_id>\d+)$', views.admin_user_delete, name='admin_user_delete'),
    path('vendor/dashboard', views.vendor_dashboard, name='vendor_dashboard'),
    path('vendor/dashboard/transaction', views.vendor_transactions, name='vendor_transactions'),
    path('vendor/dashboard/transaction/phone_verification', views.vendor_phone_verification, name='vendor_phone_verification'),
    path('vendor/dashboard/transaction/transaction/(?P<consumer_id>\d+)$', views.vendor_transaction, name='vendor_transaction'),
    # path('vendor/transactions/accept/<int:transaction_id>', views.vendor_accept, name='vendor_accept'),
    # re_path(r'^vendor/transactions/accept/(?P<transaction_id>\d+)$', views.vendor_accept, name='vendor_accept'),
    path('consumer/dashboard', views.consumer_dashboard, name='consumer_dashboard'),
    path('consumer/vendors', views.vendors, name='consumer_purchase'),
    path('consumer/vendors/<int:vendor_id>', views.vendor, name='vendor'),
]

newarkshop/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_site.urls', namespace='main_site')),
    path('users/', include('users.urls', namespace='users')),
    path('payments/', include('payments.urls', namespace='payments')),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#     import debug_toolbar
#     urlpatterns = [
#       path(r'^__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns

payments/urls.py
from django.urls import path
from . import views

app_name = 'payments'

urlpatterns = [
    # path('', views.PaymentPageView.as_view(), name='payment'),
    path('', views.home, name='payment'),
    path('charge/', views.charge, name='charge')
]

users/urls.py
"""Defines url patterns for users."""

from django.urls import path, re_path
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm
from django.urls import reverse_lazy
from django.conf import settings

app_name = 'users'

urlpatterns = [
    # Login page.
    path('login/', auth_views.LoginView.as_view(
        template_name='users/login.html', authentication_form=LoginForm
    ), name='login'),
    path('logout/', views.logout_view, name='logout'),

    path('register/consumer/stepOne', views.register_step_one, name='registerConsumerStepOne'),
    path('register/consumer/stepTwo', views.register_step_two, name='registerConsumerStepTwo'),
    path('register/consumer/stepThree', views.register_step_four, name='registerConsumerStepThree'),

    path('register/vendor/stepOne', views.register_step_one, name='registerVendorStepOne'),
    path('register/vendor/stepTwo', views.register_step_two, name='registerVendorStepTwo'),
    path('register/vendor/stepThree', views.register_step_three, name='registerVendorStepThree'),
    path('register/vendor/stepFour', views.register_step_four, name='registerVendorStepFour'),

    path('password_change', auth_views.PasswordChangeView.as_view(
            template_name='users/password_change.html',
            success_url=reverse_lazy('users:password_change_done')
        ),
        name='change_password'),
    path(r'^password_change/complete/$', auth_views.PasswordResetCompleteView.as_view(
                template_name='users/password_change_complete.html'
            ), name='password_change_done'),

    # re_path(r'^password_reset/$', views.password_reset_view, name='password_reset'),
    #re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    #         views.password_reset_confirm, name='password_reset_confirm'),

    re_path(r'^password_reset/$', auth_views.PasswordResetView.as_view(
        template_name='users/password_reset.html',
        email_template_name='users/password_reset_email.html',
        subject_template_name='users/password_reset_subject.txt',
        from_email=settings.DEFAULT_FROM_EMAIL,
        success_url=reverse_lazy('users:password_reset_done')
        ),
        name='password_reset'
    ),
    re_path(r'^password_reset/done/$', auth_views.PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'
    ), name='password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            auth_views.PasswordResetConfirmView.as_view(
                template_name='users/password_reset_confirm.html',
                success_url=reverse_lazy('users:password_reset_complete')
            ), name='password_reset_confirm'),
    re_path(r'^reset/complete/$', auth_views.PasswordResetCompleteView.as_view(
                template_name='users/password_reset_complete.html'
            ), name='password_reset_complete'),
]

main_site/models.py
from django.db import models

from users.models import CustomUser

import datetime


class Transaction(models.Model):
    vendor = models.ForeignKey(CustomUser, related_name="transaction_vendor_id", on_delete=models.CASCADE)
    consumer = models.ForeignKey(CustomUser, related_name="transaction_consumer_id", on_delete=models.CASCADE)

    amount = models.CharField(max_length=50)
    purchased_date = models.DateTimeField(default=datetime.datetime.now())

    # business_name = models.CharField(max_length=100)
    # vendor_id = models.IntegerField()
    # consumer_id = models.IntegerField()

    # line_number = models.CharField(max_length=50, default='')
    # vendor_status = models.CharField(max_length=50, default="NotAccepted")
    # consumer_status = models.CharField(max_length=50, default="NotPurchased")
    # purchased_date = models.DateTimeField(default=datetime.datetime.now())
    # accepted_date = models.DateTimeField(null=True)

    def __str__(self):
        return self.amount

main_site/forms.py
from django import forms
from .models import Transaction
from users.models import UserProfileInfo
import re


class PhoneVerificationForm(forms.Form):
    phone_number = forms.CharField(
        label='', max_length=50,
        widget=forms.TextInput(attrs={'placeholder': 'Phone 222-222-2222'})
    )

    def clean(self):
        cleaned_data = super(PhoneVerificationForm, self).clean()

        pattern = '(?:\(\d{3}\)|\d{3}-)\d{3}-\d{4}$'

        phone_number = cleaned_data.get('phone_number')

        if not is_valid(phone_number, pattern):
            self.add_error('phone_number', 'phone_number is not correct')

        users = UserProfileInfo.objects.filter(phone_number=phone_number)
        if not users.count():
            self.add_error('phone_number', 'Consumer with that number does not exist. Check your phone number.')

        return cleaned_data


class TransactionForm(forms.ModelForm):
    amount = forms.CharField(
        label='Transaction Amount',
        widget=forms.TextInput(attrs={'placeholder': 'Transaction Amount'})
    )

    class Meta:
        model = Transaction
        fields = ('amount',)

    def clean(self):
        cleaned_data = super(TransactionForm, self).clean()

        return cleaned_data


class EmailSearchForm(forms.Form):
    email = forms.CharField(
        label='Email', max_length=50,
        widget=forms.TextInput(attrs={'type': 'email'})
    )

    def clean(self):
        cleaned_data = super(EmailSearchForm, self).clean()

        return cleaned_data


def is_valid(sequence, pattern):
    match = re.match(pattern, sequence)

    if match is None:
        return False

    return True

main_site/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required

from users.models import CustomUser, UserProfileInfo
from .models import Transaction
from .forms import PhoneVerificationForm, TransactionForm, EmailSearchForm

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import datetime

from django.core.mail import send_mail
from django.core.mail import EmailMultiAlternatives


def index(request):
    """The home page for Newark Shop."""
    user = request.user
    if user.is_authenticated:
        user_type = request.user.user_type
        if user.is_superuser:
            return redirect('main_site:admin_dashboard')
        else:
            if user_type == 'vendor':
                return redirect('main_site:vendor_dashboard')
            if user_type == 'consumer':
                return redirect('main_site:consumer_dashboard')

    return render(request, 'main_site/index.html')


@login_required
def admin_dashboard(request):
    transactions_list = Transaction.objects.all()
    total_sales = 0
    for transaction in transactions_list:
        transaction.amount = set_digit_format(transaction.amount)
        total_sales += float(transaction.amount)

    total_sales = set_digit_format(total_sales)
    transaction_count = Transaction.objects.all().count()

    transactions = get_pagenatied_items(request, transactions_list)

    # for transaction in transactions:
    #     transaction.current_index = transactions.start_index() + transactions.index(transaction)

    # for i, item in enumerate(transactions):
    #     print(i == transactions.index(item))
    #     print(i)
    #     print(item)
    transactions = add_property(transactions)

    context = {
        'transactions': transactions,
        'transaction_count': transaction_count,
        'total_sales': total_sales,
    }
    return render(request, 'main_site/admin_dashboard.html', context)


@login_required
def admin_transactions(request):
    consumer_list = CustomUser.objects.raw(
        '''SELECT t.id, u.username, SUM(t.amount) total_amount
            FROM main_site_transaction as t
            RIGHT JOIN users_customuser as u ON t.consumer_id = u.id
            WHERE u.user_type = 'consumer'
            GROUP BY u.username
            ORDER BY total_amount DESC''')

    for consumer in consumer_list:
        if consumer.total_amount is None:
            consumer.total_amount = 0
        consumer.total_amount = set_digit_format(consumer.total_amount)

    consumer_count = CustomUser.objects.filter(user_type='consumer').count()
    consumers = get_pagenatied_items(request, consumer_list)
    consumers = add_property(consumers)
    context = {
        'consumers': consumers,
        'consumer_count': consumer_count
    }

    return render(request, 'main_site/admin_transactions.html', context)


@login_required
def admin_users(request):
    users_list = CustomUser.objects.filter(is_superuser=0)
    count = users_list.count()
    users = get_pagenatied_items(request, users_list)
    users = add_property(users)

    context = {
        'users': users,
        'count': count,
    }
    return render(request, 'main_site/admin_users.html', context)


@login_required
def admin_user_delete(request, user_id):
    user = CustomUser.objects.get(id=user_id)
    user.delete()

    return redirect('main_site:admin_users')


@login_required
def vendor_dashboard(request):
    transactions_list = Transaction.objects.filter(vendor_id=request.user.id)
    total_count = transactions_list.count()
    total_sales = 0
    for transaction in transactions_list:
        transaction.amount = set_digit_format(transaction.amount)
        total_sales += float(transaction.amount)

    total_sales = set_digit_format(total_sales)
    transactions = get_pagenatied_items(request, transactions_list)

    context = {
        'transactions': transactions,
        'total_count': total_count,
        'total_sales': total_sales,
        'vendor_name': request.user.userprofileinfo.business_name
    }
    return render(request, 'main_site/vendor_dashboard.html', context)


@login_required
def vendor_transactions(request):
    # transactions_list = Transaction.objects.select_related('consumer__userprofileinfo').filter(vendor_id=request.user.id)
    # transactions = get_pagenatied_items(request, transactions_list)
    #
    # context = {'transactions': transactions['data'], 'count': transactions['count']}
    # return render(request, 'main_site/vendor_transaction.html', context)
    return redirect('main_site:vendor_phone_verification')


@login_required
def vendor_phone_verification(request):
    if request.method != 'POST':
        phone_verification_form = PhoneVerificationForm()
    else:
        phone_verification_form = PhoneVerificationForm(data=request.POST)
        if phone_verification_form.is_valid():
            phone_number = phone_verification_form.data['phone_number']
            consumers = UserProfileInfo.objects.filter(phone_number=phone_number)
            # if not consumers.count():
            #     context = {'phone_verification_form': phone_verification_form, 'consumer_not_exist': True}
            #     return render(request, 'main_site/phone_verification.html', context)
            # else:
            #     consumer_id = consumers[0].user_id
            consumer_id = consumers[0].user_id
            return redirect('main_site:vendor_transaction', consumer_id)

    context = {'phone_verification_form': phone_verification_form}
    return render(request, 'main_site/phone_verification.html', context)


@login_required
def vendor_transaction(request, consumer_id):
    if request.method != 'POST':
        transaction_form = TransactionForm()
        consumer = CustomUser.objects.get(id=consumer_id)
    else:
        transaction_form = TransactionForm(data=request.POST)
        if transaction_form.is_valid():
            transaction = transaction_form.save(commit=False)
            transaction.consumer_id = consumer_id
            transaction.vendor_id = request.user.id
            transaction.save()

            return redirect('main_site:vendor_dashboard')

    context = {
        'transaction_form': transaction_form,
        'consumer': consumer
    }
    return render(request, 'main_site/vendor_transaction.html', context)


@login_required
def consumer_dashboard(request):
    transactions_list = Transaction.objects.filter(consumer_id=request.user.id)
    # transaction_count = transaction_list.count()
    # transactions = get_pagenatied_items(request, transactions_list)
    total_count = transactions_list.count()
    total_sales = 0
    for transaction in transactions_list:
        transaction.amount = set_digit_format(transaction.amount)
        total_sales += float(transaction.amount)

    total_sales = set_digit_format(total_sales)
    transactions = get_pagenatied_items(request, transactions_list)

    context = {
        'transactions': transactions,
        'total_count': total_count,
        'toatal_sales': total_sales
    }
    return render(request, 'main_site/consumer_dashboard.html', context)


@login_required
def vendors(request):
    vendor_users_list = CustomUser.objects.filter(user_type='vendor')
    vendor_users = get_pagenatied_items(request, vendor_users_list)

    context = {'vendor_users': vendor_users['data'], 'count': vendor_users['count']}
    return render(request, 'main_site/vendors.html', context)


@login_required
def vendor(request, vendor_id):
    vendor_user = CustomUser.objects.get(id=vendor_id)
    consumer_user = CustomUser.objects.get(id=request.user.id)

    if request.method != 'POST':
        transaction_form = TransactionForm()
    else:
        transaction_form = TransactionForm(data=request.POST)

        if transaction_form.is_valid():
            transaction = transaction_form.save(commit=False)
            # transaction.business_name = business_name
            transaction.vendor = vendor_user
            transaction.consumer = consumer_user
            transaction.consumer_status = 'Purchased'
            transaction.save()

            return redirect('main_site:consumer_purchase')

    context = {'vendor_user': vendor_user, 'transaction_form': transaction_form}
    return render(request, 'main_site/vendor.html', context)


def vendor_accept(request, transaction_id):
    transaction = Transaction.objects.get(id=transaction_id)
    transaction.vendor_status = 'Accepted'
    transaction.accepted_date = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S.%f")
    transaction.save()

    return redirect('main_site:vendor_transactions')


def get_pagenatied_items(request, item_list, per_page=10):
    page = request.GET.get('page', 1)

    paginator = Paginator(item_list, per_page)
    count = paginator.count
    try:
        items = paginator.page(page)
    except PageNotAnInteger:
        items = paginator.page(1)
    except EmptyPage:
        items = paginator.page(paginator.num_pages)

    # result = {'data': items, 'count': count}
    return items


def add_property(list_object):
    for item_object in list_object:
        item_object.current_index = list_object.start_index() + list_object.index(item_object)

    return list_object


def set_digit_format(_value):
    value = float(_value)
    value = "{0:.2f}".format(value)
    return value

templates/main_site/admin_dashboard.html
{% extends "main_site/base.html" %}

{% block content %}
    <div class='landing-vendor'>
        <div class="row">
            <div class="col-md-4 dashboard">
                <div class="total-transaction">
                    <h3>Total Transactions</h3>
                    <p>{{ transaction_count }}</p>
                </div>
                <div class="total-sales">
                    <h3>Total Sales</h3>
                    <p>{{ total_sales }}</p>
                </div>
            </div>
            <div class="col-md-8 dashboard-detail">
                <div class="dashboard-transaction-list">
                    <div class="detail-header">
                        <div class="row">
                            <span class="title float-left">Transaction Details</span>
                            <span class="float-right">
                                {{ transactions.start_index }}-{{ transactions.end_index }} of {{ transaction_count }}
                            </span>
                        </div>
                    </div>
                    <div class="detail-content">
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Customer ID</th>
                                <th>Phone Number</th>
                                <th>Purchase Date</th>
                                <th width="10%">Purchase Amount</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for transaction in transactions %}
                                <tr>
                                    <td>{{ transaction.current_index }}</td>
                                    <td>{{ transaction.consumer.username }}</td>
                                    <td>{{ transaction.consumer.userprofileinfo.phone_number }}</td>
                                    <td>{{ transaction.purchased_date }}</td>
                                    <td>{{ transaction.amount }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <div class="detail-footer">
                        <div class="row">
                            {% if transactions.has_other_pages %}
                                <ul class="pagination float-right">
                                    {% if transactions.has_previous %}
                                        <li><a href="?page={{ transactions.previous_page_number }}">&laquo;</a></li>
                                    {% else %}
                                        <li class="disabled"><span>&laquo;</span></li>
                                    {% endif %}
                                    {% for i in transactions.paginator.page_range %}
                                        {% if transactions.number == i %}
                                            <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                                        {% else %}
                                            <li><a href="?page={{ i }}">{{ i }}</a></li>
                                        {% endif %}
                                    {% endfor %}
                                    {% if transactions.has_next %}
                                        <li><a href="?page={{ transactions.next_page_number }}">&raquo;</a></li>
                                    {% else %}
                                        <li class="disabled"><span>&raquo;</span></li>
                                    {% endif %}
                                </ul>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/main_site/admin_transactions.html
{% extends "main_site/base.html" %}

{% block content %}
    <div class='landing-vendor'>
        <div class="dashboard-transaction-list">
            <div class="detail-header">
                <div class="row">
                    <span class="title float-left">Transaction Details</span>
                    <span class="float-right">
                        {{ consumers.start_index }}-{{ consumers.end_index }} of {{ consumer_count }}
                    </span>
                </div>
            </div>
            <div class="detail-content">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Customer ID</th>
                        <th>Total Purchase Amount</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for consumer in consumers %}
                        <tr>
                            <td>{{ consumer.current_index }}</td>
                            <td>{{ consumer.username }}</td>
                            <td>{{ consumer.total_amount }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="detail-footer">
                <div class="row">
                    {% if consumers.has_other_pages %}
                        <ul class="pagination float-right">
                            {% if consumers.has_previous %}
                                <li><a href="?page={{ consumers.previous_page_number }}">&laquo;</a></li>
                            {% else %}
                                <li class="disabled"><span>&laquo;</span></li>
                            {% endif %}
                            {% for i in consumers.paginator.page_range %}
                                {% if consumers.number == i %}
                                    <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                                {% else %}
                                    <li><a href="?page={{ i }}">{{ i }}</a></li>
                                {% endif %}
                            {% endfor %}
                            {% if consumers.has_next %}
                                <li><a href="?page={{ consumers.next_page_number }}">&raquo;</a></li>
                            {% else %}
                                <li class="disabled"><span>&raquo;</span></li>
                            {% endif %}
                        </ul>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/main_site/admin_users.html
{% extends "main_site/base.html" %}

{% block content %}
    <div class='landing-vendor'>
        <div class="row">
            <div class="dashboard-detail">
                <div class="detail-header">
                    <div class="row">
                        <span class="title float-left">User List</span>
                        <span class="float-right">
                            {{ users.start_index }} - {{ users.end_index }} of {{ count }}
                        </span>
                    </div>
                </div>
                <div class="detail-content">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Email</th>
                            <th>Phone Number</th>
                            <th>User Type</th>
                            <th>action</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for user in users %}
                            <tr>
                                <td>{{ user.current_index }}</td>
                                <td>{{ user.email }}</td>
                                <td>{{ user.userprofileinfo.phone_number }}</td>
                                <td>{{ user.user_type }}</td>
                                <td>
                                    <a href="{% url 'main_site:admin_user_delete' user.id %}" class="btn btn-primary">delete</a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="detail-footer">
                    <div class="row">
                        {% if users.has_other_pages %}
                            <ul class="pagination float-right">
                                {% if users.has_previous %}
                                    <li><a href="?page={{ users.previous_page_number }}">&laquo;</a></li>
                                {% else %}
                                    <li class="disabled"><span>&laquo;</span></li>
                                {% endif %}
                                {% for i in users.paginator.page_range %}
                                    {% if users.number == i %}
                                        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                                    {% else %}
                                        <li><a href="?page={{ i }}">{{ i }}</a></li>
                                    {% endif %}
                                {% endfor %}
                                {% if users.has_next %}
                                    <li><a href="?page={{ users.next_page_number }}">&raquo;</a></li>
                                {% else %}
                                    <li class="disabled"><span>&raquo;</span></li>
                                {% endif %}
                            </ul>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/main_site/base.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block navbar-nav %}
    {% if user.is_superuser %}
        <li><a href="{% url 'main_site:admin_transactions' %}">Transactions</a>
        <li><a href="{% url 'main_site:admin_users' %}">Users</a>
    {% else %}
        {% if user.user_type == 'vendor' %}
            <li><a href="{% url 'main_site:vendor_transactions' %}">Transaction</a>
            <li><a href="{% url 'payments:payment' %}">Payment</a>
        {% endif %}
        {% if user.user_type == 'consumer' %}
        {% endif %}
    {% endif %}
{% endblock %}

{% block navbar-right %}
    <li><a>Welcome {{ user.first_name }} {{ user.last_name }}!</a></li>
{#    <li><a>Account</a></li>#}
{% endblock %}

{% block header %}
    <div class="landing-vendor">
        <div class="logo-div">
            <img src="/static/img/logo.png" />
        </div>
    </div>
{% endblock %}

templates/main_site/vendor.html
{% extends "main_site/base.html" %}
{% load bootstrap3 %}

{% block content %}
    <h2>Business Name : {{ vendor_user.userprofileinfo.business_name }}</h2>

    <form enctype="multipart/form-data" method="post"
              action="{% url 'main_site:vendor' vendor_user.id %}">

        {% csrf_token %}

        {% bootstrap_form transaction_form %}

        <button name="submit" class="btn btn-primary">purchase</button>
    </form>
{% endblock %}

templates/main_site/vendors.html
{% extends "main_site/base.html" %}

{% block content %}
    <div class='vendors'>
        <div class="vendors-detail">
            <div class="detail-header">
                <div class="row">
                    <span class="title float-left">Vendors List</span>
                    <span class="float-right">
                        {{ vendor_users.start_index }}-{{ vendor_users.end_index }} of {{ count }}
                    </span>
                </div>
            </div>
            <div class="detail-content">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <td>No</td>
                        <th>Business Name</th>
                        <th>Address</th>
                        <th>action</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for vendor in vendor_users %}
                        <tr>
                            <td>{{ forloop.counter }} </td>
                            <td>{{ vendor.userprofileinfo.business_name }}</td>
                            <td>{{ vendor.userprofileinfo.address_line_one }}</td>
                            <td><a href="{% url 'main_site:vendor' vendor.userprofileinfo.user_id %}" class="btn btn-primary">purchase</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="detail-footer">
                {% if transactions.has_other_pages %}
                    <ul class="pagination float-right">
                        {% if transactions.has_previous %}
                            <li><a href="?page={{ transactions.previous_page_number }}">&laquo;</a></li>
                        {% else %}
                            <li class="disabled"><span>&laquo;</span></li>
                        {% endif %}
                        {% for i in transactions.paginator.page_range %}
                            {% if transactions.number == i %}
                                <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                            {% else %}
                                <li><a href="?page={{ i }}">{{ i }}</a></li>
                            {% endif %}
                        {% endfor %}
                        {% if transactions.has_next %}
                            <li><a href="?page={{ transactions.next_page_number }}">&raquo;</a></li>
                        {% else %}
                            <li class="disabled"><span>&raquo;</span></li>
                        {% endif %}
                    </ul>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}