main_site/urls.py
from django.urls import path, re_path

from . import views

app_name = 'main_site'

urlpatterns = [
    # Home page.
    path('', views.index, name='index'),
    path('admin/dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('admin/dashboard/transactions', views.admin_transactions, name='admin_transactions'),
    path('admin/dashboard/users', views.admin_users, name='admin_users'),
    path('admin/dashboard/users/delete/(?P<user_id>\d+)$', views.admin_user_delete, name='admin_user_delete'),
    path('vendor/dashboard', views.vendor_dashboard, name='vendor_dashboard'),
    path('vendor/dashboard/transaction', views.vendor_transactions, name='vendor_transactions'),
    path('vendor/dashboard/transaction/phone_verification', views.vendor_phone_verification, name='vendor_phone_verification'),
    path('vendor/dashboard/transaction/transaction/(?P<consumer_id>\d+)$', views.vendor_transaction, name='vendor_transaction'),
    # path('vendor/transactions/accept/<int:transaction_id>', views.vendor_accept, name='vendor_accept'),
    # re_path(r'^vendor/transactions/accept/(?P<transaction_id>\d+)$', views.vendor_accept, name='vendor_accept'),
    path('consumer/dashboard', views.consumer_dashboard, name='consumer_dashboard'),
    path('consumer/vendors', views.vendors, name='consumer_purchase'),
    path('consumer/vendors/<int:vendor_id>', views.vendor, name='vendor'),
]

newarkshop/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_site.urls', namespace='main_site')),
    path('users/', include('users.urls', namespace='users')),
    path('payments/', include('payments.urls', namespace='payments')),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#     import debug_toolbar
#     urlpatterns = [
#       path(r'^__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns

users/urls.py
"""Defines url patterns for users."""

from django.urls import path, re_path
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm
from django.urls import reverse_lazy
from django.conf import settings

app_name = 'users'

urlpatterns = [
    # Login page.
    path('login/', auth_views.LoginView.as_view(
        template_name='users/login.html', authentication_form=LoginForm
    ), name='login'),
    path('logout/', views.logout_view, name='logout'),

    path('register/consumer/stepOne', views.register_step_one, name='registerConsumerStepOne'),
    path('register/consumer/stepTwo', views.register_step_two, name='registerConsumerStepTwo'),
    path('register/consumer/stepThree', views.register_step_four, name='registerConsumerStepThree'),

    path('register/vendor/stepOne', views.register_step_one, name='registerVendorStepOne'),
    path('register/vendor/stepTwo', views.register_step_two, name='registerVendorStepTwo'),
    path('register/vendor/stepThree', views.register_step_three, name='registerVendorStepThree'),
    path('register/vendor/stepFour', views.register_step_four, name='registerVendorStepFour'),

    path('password_change', auth_views.PasswordChangeView.as_view(
            template_name='users/password_change.html',
            success_url=reverse_lazy('users:password_change_done')
        ),
        name='change_password'),
    path(r'^password_change/complete/$', auth_views.PasswordResetCompleteView.as_view(
                template_name='users/password_change_complete.html'
            ), name='password_change_done'),

    # re_path(r'^password_reset/$', views.password_reset_view, name='password_reset'),
    #re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    #         views.password_reset_confirm, name='password_reset_confirm'),

    re_path(r'^password_reset/$', auth_views.PasswordResetView.as_view(
        template_name='users/password_reset.html',
        email_template_name='users/password_reset_email.html',
        subject_template_name='users/password_reset_subject.txt',
        from_email=settings.DEFAULT_FROM_EMAIL,
        success_url=reverse_lazy('users:password_reset_done')
        ),
        name='password_reset'
    ),
    re_path(r'^password_reset/done/$', auth_views.PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'
    ), name='password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            auth_views.PasswordResetConfirmView.as_view(
                template_name='users/password_reset_confirm.html',
                success_url=reverse_lazy('users:password_reset_complete')
            ), name='password_reset_confirm'),
    re_path(r'^reset/complete/$', auth_views.PasswordResetCompleteView.as_view(
                template_name='users/password_reset_complete.html'
            ), name='password_reset_complete'),
]

templates/base.html
{% load bootstrap3 %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Newark Shop</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}

    <script src="{% static 'js/main.js' %}"></script> <!-- This is how to include a static file -->
    <link rel="stylesheet" href="{% static 'css/reset.css' %}" type="text/css" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css" />
</head>

<body>

<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed"
                    data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'main_site:index' %}">
                Home</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                {% block navbar-nav %}{% endblock %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
{#                    <li><a>Hello, {{ user.username }}.</a></li>#}
                    {% block navbar-right %}{% endblock %}
                    <li><a href="{% url 'users:change_password' %}">Change Password</a></li>
                    <li><a href="{% url 'users:logout' %}">Sign out</a></li>
                {% else %}
                    <li><a href="{% url 'users:registerConsumerStepOne' %}">Consumer Register</a></li>
                    <li><a href="{% url 'users:registerVendorStepOne' %}">Vendor Register</a></li>
                    <li><a href="{% url 'users:login' %}">log in</a></li>
                {% endif %}
            </ul>
        </div><!--/.nav-collapse -->

    </div>
</nav>

<div class="container">

    <div class="page-header">
        {% block header %}{% endblock %}
    </div>
    <div class="page-content">
        {% block content %}{% endblock %}
    </div>

</div> <!-- /container -->

</body>
</html>