main_site/urls.py
from django.urls import path, re_path

from . import views

app_name = 'main_site'

urlpatterns = [
    # Home page.
    path('', views.index, name='index'),
    path('admin/dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('admin/dashboard/transactions', views.admin_transactions, name='admin_transactions'),
    path('admin/dashboard/users', views.admin_users, name='admin_users'),
    path('admin/dashboard/users/delete/(?P<user_id>\d+)$', views.admin_user_delete, name='admin_user_delete'),
    path('vendor/dashboard', views.vendor_dashboard, name='vendor_dashboard'),
    path('vendor/dashboard/transaction', views.vendor_transactions, name='vendor_transactions'),
    path('vendor/dashboard/transaction/phone_verification', views.vendor_phone_verification, name='vendor_phone_verification'),
    path('vendor/dashboard/transaction/transaction/(?P<consumer_id>\d+)$', views.vendor_transaction, name='vendor_transaction'),
    # path('vendor/transactions/accept/<int:transaction_id>', views.vendor_accept, name='vendor_accept'),
    # re_path(r'^vendor/transactions/accept/(?P<transaction_id>\d+)$', views.vendor_accept, name='vendor_accept'),
    path('consumer/dashboard', views.consumer_dashboard, name='consumer_dashboard'),
    path('consumer/vendors', views.vendors, name='consumer_purchase'),
    path('consumer/vendors/<int:vendor_id>', views.vendor, name='vendor'),
]

newarkshop/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_site.urls', namespace='main_site')),
    path('users/', include('users.urls', namespace='users')),
    path('payments/', include('payments.urls', namespace='payments')),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#     import debug_toolbar
#     urlpatterns = [
#       path(r'^__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns

users/urls.py
"""Defines url patterns for users."""

from django.urls import path, re_path
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm
from django.urls import reverse_lazy
from django.conf import settings

app_name = 'users'

urlpatterns = [
    # Login page.
    path('login/', auth_views.LoginView.as_view(
        template_name='users/login.html', authentication_form=LoginForm
    ), name='login'),
    path('logout/', views.logout_view, name='logout'),

    path('register/consumer/stepOne', views.register_step_one, name='registerConsumerStepOne'),
    path('register/consumer/stepTwo', views.register_step_two, name='registerConsumerStepTwo'),
    path('register/consumer/stepThree', views.register_step_four, name='registerConsumerStepThree'),

    path('register/vendor/stepOne', views.register_step_one, name='registerVendorStepOne'),
    path('register/vendor/stepTwo', views.register_step_two, name='registerVendorStepTwo'),
    path('register/vendor/stepThree', views.register_step_three, name='registerVendorStepThree'),
    path('register/vendor/stepFour', views.register_step_four, name='registerVendorStepFour'),

    path('password_change', auth_views.PasswordChangeView.as_view(
            template_name='users/password_change.html',
            success_url=reverse_lazy('users:password_change_done')
        ),
        name='change_password'),
    path(r'^password_change/complete/$', auth_views.PasswordResetCompleteView.as_view(
                template_name='users/password_change_complete.html'
            ), name='password_change_done'),

    # re_path(r'^password_reset/$', views.password_reset_view, name='password_reset'),
    #re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    #         views.password_reset_confirm, name='password_reset_confirm'),

    re_path(r'^password_reset/$', auth_views.PasswordResetView.as_view(
        template_name='users/password_reset.html',
        email_template_name='users/password_reset_email.html',
        subject_template_name='users/password_reset_subject.txt',
        from_email=settings.DEFAULT_FROM_EMAIL,
        success_url=reverse_lazy('users:password_reset_done')
        ),
        name='password_reset'
    ),
    re_path(r'^password_reset/done/$', auth_views.PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'
    ), name='password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            auth_views.PasswordResetConfirmView.as_view(
                template_name='users/password_reset_confirm.html',
                success_url=reverse_lazy('users:password_reset_complete')
            ), name='password_reset_confirm'),
    re_path(r'^reset/complete/$', auth_views.PasswordResetCompleteView.as_view(
                template_name='users/password_reset_complete.html'
            ), name='password_reset_complete'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser


class CustomUser(AbstractUser):
    user_type = models.CharField(max_length=10, null=True)


class UserProfileInfo(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)

    business_name = models.CharField(max_length=100)
    # first_name = models.CharField(max_length=50)
    # last_name = models.CharField(max_length=50)
    address_line_one = models.CharField(max_length=50)
    address_line_two = models.CharField(max_length=50, null=True)
    city = models.CharField(max_length=50)
    st = models.CharField(max_length=50)
    zip_code = models.CharField(max_length=50)
    phone_number = models.CharField(max_length=50)
    of_employees = models.CharField(max_length=50, null=True)
    company = models.CharField(max_length=50)
    # of_employees = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


class UserPaymentInfo(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)

    pay_amount = models.CharField(max_length=10, blank=True)
    card_number = models.CharField(max_length=50)
    exp_date = models.DateField(blank=True)
    cvv = models.CharField(max_length=10)

    def __str__(self):
        return self.user.username

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, SetPasswordForm
from .models import UserProfileInfo, UserPaymentInfo
from .models import CustomUser

import re


class LoginForm(AuthenticationForm):
    username = forms.CharField(
        label='Email Address', max_length=30,
        widget=forms.TextInput(attrs={'class': 'loginput'})
    )


class UserForm(forms.ModelForm):
    password = forms.CharField(label='Password*', widget=forms.PasswordInput())
    confirm_password = forms.CharField(label='Confirm Password*', widget=forms.PasswordInput())

    class Meta:
        model = CustomUser
        widgets = {
            'username': forms.EmailInput(attrs={
                'placeholder': 'Email',
            }),
            'email': forms.HiddenInput,
            'first_name': forms.TextInput(attrs={
                'placeholder': 'First Name',
            }),
            'last_name': forms.TextInput(attrs={
                'placeholder': 'Last Name',
            }),
        }
        labels = {
            'username': 'Email Address',
            "first_name": '',
            "last_name": '',
        }
        help_texts = {
            'username': ''
        }
        error_messages = {
            'username': {
                'unique': "A user with that EmailAddress already exists.",
            }
        }

        fields = (
            'username', 'password', 'confirm_password', 'email',
            'first_name', 'last_name'
        )

    def clean(self):
        cleaned_data = super(UserForm, self).clean()

        pattern = "^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,}$"
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password is not None and confirm_password is not None:
            if not is_valid(password, pattern):
                self.add_error('password', "Password must contain: 8Characters l letter 1 number")
            if password != confirm_password:
                self.add_error('confirm_password', "Password does not match")

        return cleaned_data

    # def save(self, commit=True):
    #     user = super().save(False)
    #     user.email = user.username
    #     user = super().save()
    #
    #     return user


class UserProfileInfoForm(forms.ModelForm):
    business_name = forms.CharField(
        label='Business Name*', max_length=100,
        widget=forms.TextInput(attrs={'placeholder': ''})
    )
    address_line_one = forms.CharField(
        label='', max_length=50,
        widget=forms.TextInput(attrs={'placeholder': 'Address Line1'})
    )
    address_line_two = forms.CharField(
        label='', max_length=50, required=False,
        widget=forms.TextInput(attrs={'placeholder': 'Address Line2'})
    )
    city = forms.CharField(
        label='', max_length=50,
        widget=forms.TextInput(attrs={'placeholder': 'City'})
    )
    st = forms.CharField(
        label='', max_length=50,
        widget=forms.TextInput(attrs={'placeholder': 'ST'})
    )
    zip_code = forms.CharField(
        label='', max_length=50,
        widget=forms.TextInput(attrs={'type': 'number', 'placeholder': 'Zip Code'})
    )
    phone_number = forms.CharField(
        label='', max_length=50,
        widget=forms.TextInput(attrs={'type': 'text', 'placeholder': 'Phone 222-222-2222'})
    )
    of_employees = forms.CharField(
        label='# of Employees(Optional)', max_length=50, required=False,
        widget=forms.TextInput()
    )
    company = forms.CharField(
        label='Company*', max_length=50,
        widget=forms.TextInput(attrs={'placeholder': ''})
    )

    class Meta:
        model = UserProfileInfo
        fields = (
            'business_name', 'address_line_one',
            'address_line_two', 'city', 'st', 'zip_code', 'phone_number',
            'of_employees', 'company'
        )

    def clean(self):
        cleaned_data = super(UserProfileInfoForm, self).clean()

        pattern = '(?:\(\d{3}\)|\d{3}-)\d{3}-\d{4}$'

        phone_number = cleaned_data.get('phone_number')

        if not is_valid(phone_number, pattern):
            self.add_error('phone_number', 'phone_number format is not correct')

        users = UserProfileInfo.objects.filter(phone_number=phone_number)
        if users.count() > 0:
            self.add_error('phone_number', 'phone_number is already exist')

        return cleaned_data


class UserPaymentInfoForm(forms.ModelForm):
    card_number = forms.CharField(
        label='Credit Card',
        widget=forms.TextInput(attrs={'placeholder': '4242-4242-4242-4242'})
    )
    exp_date = forms.DateField(
        label='Expiration',
        widget=forms.TextInput(attrs={'type': 'date', 'placeholder': 'MM/YY'})
    )
    cvv = forms.CharField(
        label='cvv', max_length=10,
        widget=forms.TextInput(attrs={'type': 'number'})
    )

    class Meta:
        model = UserPaymentInfo
        fields = (
            'card_number', 'exp_date', 'cvv'
        )

    def clean(self):
        cleaned_data = super(UserPaymentInfoForm, self).clean()

        pattern = '\d{4}-\d{4}-\d{4}-\d{4}'

        card_number = cleaned_data.get("card_number")

        if not is_valid(card_number, pattern):
            self.add_error('card_number', "card_number format is not correct")

        return cleaned_data


def is_valid(sequence, pattern):
    """Returns `True' if the sequence is a valid credit card number.

    A valid credit card number
    - must contain exactly 16 digits,
    - must start with a 4, 5 or 6
    - must only consist of digits (0-9) or hyphens '-',
    - may have digits in groups of 4, separated by one hyphen "-".
    - must NOT use any other separator like ' ' , '_',
    - must NOT have 4 or more consecutive repeated digits.
    """

    match = re.match(pattern, sequence)

    if match is None:
        return False

    return True

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate

from .forms import UserForm, UserProfileInfoForm, UserPaymentInfoForm

from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import SetPasswordForm
from django.urls import reverse_lazy
from django.conf import settings


def logout_view(request):
    """Log the user out."""
    logout(request)
    return redirect('main_site:index')


def register_consumer_view(request):
    if request.method != 'POST':
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    else:
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            new_user = user_form.save()
            new_user.email = new_user.username
            new_user.set_password(new_user.password)
            new_user.user_type = 'consumer'
            profile = profile_form.save(commit=False)
            profile.user = new_user

            new_user.save()
            profile.save()

            return redirect('main_site:index')

    context = {'user_form': user_form, 'profile_form': profile_form}
    return render(request, 'users/register_consumer.html', context)


def register_step_one(request):
    user_type = get_user_type(request)

    if request.method != 'POST':
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    else:
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            if user_type == 'consumer':
                return redirect('users:registerConsumerStepTwo')
            elif user_type == 'vendor':
                return redirect('users:registerVendorStepTwo')

    context = {'user_form': user_form, 'profile_form': profile_form, 'user_type': user_type}
    return render(request, 'users/register_step1.html', context)


def register_step_two(request):
    return render(request, 'users/register_step2.html')


def register_step_three(request):
    if request.method != 'POST':
        payment_form = UserPaymentInfoForm()
    else:
        payment_form = UserPaymentInfoForm(data=request.POST)
        if payment_form.is_valid():
            return redirect('users:registerVendorStepFour')

    context = {'payment_form': payment_form}
    return render(request, 'users/register_step3.html', context)


def register_step_four(request):
    user_type = get_user_type(request)
    """Register a new user."""
    if request.method != 'POST':
        # Display blank registration form.
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
        payment_form = UserPaymentInfoForm()
    else:
        # Process completed form.
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        payment_form = UserPaymentInfoForm(data=request.POST)

        if user_type == 'consumer':
            if user_form.is_valid() and profile_form.is_valid():
                new_user = user_form.save()
                new_user.email = new_user.username
                new_user.set_password(new_user.password)
                new_user.user_type = user_type
                new_user.first_name = new_user.first_name.capitalize()
                new_user.last_name = new_user.last_name.capitalize()

                profile = profile_form.save(commit=False)
                profile.user = new_user

                new_user.save()
                profile.save()

        elif user_type == 'vendor':
            if user_form.is_valid() and profile_form.is_valid() and payment_form.is_valid():
                new_user = user_form.save()
                new_user.email = new_user.username
                new_user.set_password(new_user.password)
                new_user.user_type = user_type
                new_user.first_name = new_user.first_name.capitalize()
                new_user.last_name = new_user.last_name.capitalize()

                profile = profile_form.save(commit=False)
                profile.user = new_user

                payment = payment_form.save(commit=False)
                payment.user = new_user
                payment.pay_amount = 20

                new_user.save()
                profile.save()
                payment.save()
                # Log the user in, and then redirect to home page.
                # authenticated_user = authenticate(username=new_user.username,
                #                                   password=request.POST['password1'])
                # login(request, authenticated_user)
        else:
            pass

        return redirect('main_site:index')

    context = {'user_form': user_form, 'profile_form': profile_form,
               'payment_form': payment_form, 'user_type': user_type}
    return render(request, 'users/register_step4.html', context)


def get_user_type(request):
    path = request.path
    if path.find('vendor') > 0:
        user_type = 'vendor'
    elif path.find('consumer') > 0:
        user_type = 'consumer'
    else:
        user_type = 'admin'

    return user_type

templates/users/login.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Login
                </div>
                <div class="panel-body">
                    <form method="post" action="{% url 'users:login' %}" class="form">
                        {% csrf_token %}
                        {% bootstrap_form form %}

                        <div class="form-group">
                            <button name="submit" class="btn btn-primary">Log in</button>
                            <a href="{% url 'users:password_reset' %}" class="btn btn-link">Forgot Your Password?</a>
                        </div>
                        <input type="hidden" name="next" value="{% url 'main_site:index' %}" />
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

templates/users/password_change.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Change Password
                </div>
                <div class="panel-body">
                    <form method="post">
                        {% csrf_token %}
                        {% bootstrap_form form %}
                        <button type="submit" class="btn btn-primary">Change Password</button>
                    </form>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

templates/users/password_change_complete.html
{% extends 'base.html' %}

{% block content %}
  <p>
    Your password has been changed. You may go ahead and
      <a href="{% url 'users:login' %}">sign in</a> now.
  </p>
{% endblock %}

templates/users/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}
  <p>
    Your password has been set. You may go ahead and
      <a href="{% url 'users:login' %}">sign in</a> now.
  </p>
{% endblock %}

templates/users/password_reset_email.html
{% autoescape off %}
To initiate the password reset process for your {{ user.get_username }} NewarkShop Account,
click the link below:

{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

Sincerely,
The NewarkShop Team
{% endautoescape %}

templates/users/register_consumer.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
    <form enctype="multipart/form-data" method="post"
          action="{% url 'users:registerConsumer' %}" id="registerForm" name="registerForm">
        {% csrf_token %}
        <div class="profile-main show">
            <h1 class="register-title">CONSUMER-Create an Account</h1>
            <div class="form-group">
                <label class="control-label" for="id_first_name">Contract*</label>
                <div class="row">
                    <div class="col-md-6">
                        {%  bootstrap_field profile_form.first_name %}
                    </div>
                    <div class="col-md-6">
                        {%  bootstrap_field profile_form.last_name %}
                    </div>
                </div>
            </div>
            <label class="control-label" for="id_address_line1">Address*</label>
            {%  bootstrap_field profile_form.address_line1 %}
            {%  bootstrap_field profile_form.address_line2 %}
            <div class="form-group">
                <div class="row">
                    <div class="col-md-10">
                        {%  bootstrap_field profile_form.city %}
                    </div>
                    <div class="col-md-2">
                        {%  bootstrap_field profile_form.st %}
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-md-5">
                        {%  bootstrap_field profile_form.zip_code %}
                    </div>
                    <div class="col-md-7">
                        {%  bootstrap_field profile_form.phone_number %}
                    </div>
                </div>
            </div>

            {% bootstrap_form user_form %}
            {%  bootstrap_field profile_form.of_employees %}

            <a class="btn btn-primary">Next</a>
        </div>
        <div class="profile-terms-agree">
            <h1 class="register-title">Terms & Conditions</h1>
            <div>
                <div class="agree-content"></div>
                <div class="checkbox checkbox-agree">
                    <label for="id_agree">
                        <input type="checkbox" name="of_employees" class="" id="id_agree">I Agree
                    </label>
                </div>
            </div>
            <a class="btn btn-primary">Next</a>
        </div>
        <div class="profile-confirm">
            <hl class="register-title">Consumer-Confirmation Page</hl>
            <p>
                First Name : <span class="confirm-first-name"></span>
                Last Name : <span class="confirm-last-name"></span>
            </p>
            <p>Business Address 1 : <span class="confirm-business-address1"></span></p>
            <p>Business Address 2 : <span class="confirm-business-address2"></span></p>
            <p>City : <span class="confirm-city"></span></p>
            <p>
                ST : <span class="confirm-st"></span>
                ZIP Code : <span class="confirm-zip-code"></span>
            </p>
            <p>Phone : <span class="confirm-phone-number"></span></p>
            <p>Email Address : <span class="confirm-email-address"></span></p>

            <button name="submit" class="btn btn-primary">register</button>
            <input type="hidden" name="next" value="{% url 'main_site:index' %}" />
            <input type="hidden" name="status" id="status" value="" />
        </div>
    </form>

    <script>
        $(document).ready(function(){
            {#$(".page-content > form > div").hide();#}

            $(".page-content > form > div > a").click(function () {
                if($(this).parent().hasClass('profile-terms-agree')){
                    if($('#id_agree').prop('checked') == false) return;
                }

                if($(this).parent().next().hasClass('profile-confirm')){
                    setProfileConfirmView();
                }

                $(this).parent().removeClass('show');
                $(this).parent().next().addClass('show');
            });

        });
        function setProfileConfirmView() {
            $('.confirm-email-address').text($('#id_username').val());
            $('.confirm-first-name').text($('#id_first_name').val());
            $('.confirm-last-name').text($('#id_last_name').val());
            $('.confirm-business-address1').text($('#id_address_line1').val());
            $('.confirm-business-address2').text($('#id_address_line2').val());
            $('.confirm-city').text($('#id_city').val());
            $('.confirm-st').text($('#id_st').val());
            $('.confirm-zip-code').text($('#id_zip_code').val());
            $('.confirm-phone-number').text($('#id_phone_number').val());
            $('.confirm-email-address').text($('#id_username').val());

        }

    </script>

{% endblock content %}

templates/users/register_vendor.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
    <form enctype="multipart/form-data" method="post"
          action="{% url 'users:registerAsVendor' %}" id="registerForm" name="registerForm">
        {% csrf_token %}
        <div class="profile-main show">
            <h1>NEW VENDORS-Create an Account</h1>
            {#        {% bootstrap_form profile_form %}#}

            {%  bootstrap_field profile_form.business_name %}
            <div class="form-group">
                <label class="control-label" for="id_first_name">Business Contract*</label>
                <div class="row">
                    <div class="col-md-6">
                        {%  bootstrap_field profile_form.first_name %}
                    </div>
                    <div class="col-md-6">
                        {%  bootstrap_field profile_form.last_name %}
                    </div>
                </div>
            </div>
            {%  bootstrap_field profile_form.address_line1 %}
            {%  bootstrap_field profile_form.address_line2 %}
            <div class="form-group">
                <div class="row">
                    <div class="col-md-10">
                        {%  bootstrap_field profile_form.city %}
                    </div>
                    <div class="col-md-2">
                        {%  bootstrap_field profile_form.st %}
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-md-5">
                        {%  bootstrap_field profile_form.zip_code %}
                    </div>
                    <div class="col-md-7">
                        {%  bootstrap_field profile_form.phone_number %}
                    </div>
                </div>
            </div>
            {%  bootstrap_field profile_form.of_employees %}

            {% bootstrap_form user_form %}

            <a class="btn btn-primary">Next</a>
        </div>
        <div class="profile-terms-agree">
            <h1>Terms & Conditions</h1>
            <div>
                <div class="agree-content"></div>
                <div class="checkbox checkbox-agree">
                    <label for="id_agree">
                        <input type="checkbox" name="of_employees" class="" id="id_agree">I Agree
                    </label>
                </div>
            </div>
            <a class="btn btn-primary">Next</a>
        </div>
        <div class="profile-payment">
            <h1>NEW VENDORS-Payment</h1>
            <h2>Monthly Subscription</h2>
            <p>$20</p>
            {% bootstrap_field payment_form.card_number %}
            <div class="form-group">
                <div class="row">
                    <div class="col-md-6">
                        {% bootstrap_field payment_form.exp_date %}
                    </div>
                    <div class="col-md-6">
                        {% bootstrap_field payment_form.cvv %}
                    </div>
                </div>
            </div>
            <a class="btn btn-primary">Next</a>
        </div>
        <div class="profile-confirm">
            <p>Business Name : <span class="confirm-email-address"></span></p>
            <p>
                First Name : <span class="confirm-first-name"></span>
                Last Name : <span class="confirm-last-name"></span>
            </p>
            <p>Business Address 1 : <span class="confirm-business-address1"></span></p>
            <p>Business Address 2 : <span class="confirm-business-address2"></span></p>
            <p>City : <span class="confirm-city"></span></p>
            <p>
                ST : <span class="confirm-st"></span>
                ZIP Code : <span class="confirm-zip-code"></span>
            </p>
            <p>Phone : <span class="confirm-phone-number"></span></p>
            <p>Email Address : <span class="confirm-email-address"></span></p>

            <h2>Payment Information</h2>
            <p>Credit Card : <span class="confirm-card-number"></span></p>
            <p>
                Exp : <span class="confirm-exp-date"></span>
                CVV : <span class="confirm-cvv"></span>
            </p>

            <button name="submit" class="btn btn-primary">register</button>
            <input type="hidden" name="next" value="{% url 'main_site:index' %}" />
            <input type="hidden" name="status" id="status" value="" />
        </div>
    </form>


    <script>
        $(document).ready(function(){
            {#$(".page-content > form > div").hide();#}

            $(".page-content > form > div > a").click(function () {
                if($(this).parent().hasClass('profile-terms-agree')){
                    if($('#id_agree').prop('checked') == false) return;
                }

                if($(this).parent().next().hasClass('profile-confirm')){
                    setProfileConfirmView();
                }

                $(this).parent().removeClass('show');
                $(this).parent().next().addClass('show');
            });

        });
        function setProfileConfirmView() {
            $('.confirm-email-address').text($('#id_username').val());
            $('.confirm-first-name').text($('#id_first_name').val());
            $('.confirm-last-name').text($('#id_last_name').val());
            $('.confirm-business-address1').text($('#id_address_line1').val());
            $('.confirm-business-address2').text($('#id_address_line2').val());
            $('.confirm-city').text($('#id_city').val());
            $('.confirm-st').text($('#id_st').val());
            $('.confirm-zip-code').text($('#id_zip_code').val());
            $('.confirm-phone-number').text($('#id_phone_number').val());
            $('.confirm-email-address').text($('#id_username').val());

            $('.confirm-card-number').text($('#id_card_number').val());
            $('.confirm-exp-date').text($('#id_exp_date').val());
            $('.confirm-cvv').text($('#id_cvv').val());
        }

        function goNext(obj) {
            if($(obj).parent().hasClass('profile-confirm')){
                $('#status').val('final');
            }
            if($(obj).parent().hasClass('profile-terms-agree')){
                if($('#id_agree').prop('checked') == false) return;
            }

            $(obj).parent().removeClass('show');
            $(obj).parent().next().addClass('show');
        }
    </script>

{% endblock content %}